In [142]:
from roboflow import Roboflow
import matplotlib.pyplot as plt
import cv2
from tensorflow.keras.utils import load_img, img_to_array
import os
import numpy as np
import tensorflow as tf

rf = Roboflow(api_key="YOUR_API")
project = rf.workspace("coins-pw0uj").project("coins-tunisia")
version = project.version(2)
dataset = version.download("yolov5")
model = project.version(1).model


loading Roboflow workspace...
loading Roboflow project...


In [148]:
#preparing test data

xi,yi=150,150
size=(xi,yi,3)

ls=[]
x_test=[]
y_test=[]

path_images_test_0="D:/dataset/test/100"
images_0 = os.listdir(path_images_test_0)

for img_name in images_0:
    path_img= os.path.join(path_images_test_0,img_name) #getting the path of an image

    image = load_img(path_img, target_size=size) #upploading the image
    image = img_to_array(image) #getting the array values of the image
    #print(image)
    image_grayscale = tf.image.rgb_to_grayscale(image) #converting the RGB image into grayscale
    image_grayscale = np.array(image_grayscale)
    #print(image_grayscale)
    x_test.append(image_grayscale)
    y_test.append(100)


path_images_test_0="D:/dataset/test/50"
images_0 = os.listdir(path_images_test_0)

for img_name in images_0:
    path_img= os.path.join(path_images_test_0,img_name) #getting the path of an image

    image = load_img(path_img, target_size=size) #upploading the image
    image = img_to_array(image) #getting the array values of the image
    #print(image)
    image_grayscale = tf.image.rgb_to_grayscale(image) #converting the RGB image into grayscale
    image_grayscale = np.array(image_grayscale)
    #print(image_grayscale)
    x_test.append(image_grayscale)
    y_test.append(50)



x_test=np.array(x_test)
y_test=np.array(y_test)

In [149]:
#prediction
y_pred=[]

for test in x_test:
  test=img_to_array(test)

  responce=model.predict(test,confidence=5,overlap=40).json()
  somme=sum([int(i["class"]) for i in responce['predictions']])
  print(somme)
  y_pred.append(somme)

y_pred=np.array(y_pred)
print("prediction: ", y_pred)
print("ground truth: ", y_test)

#confusion matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('acc=',accuracy_score(y_test,y_pred))

100
100
200
200
prediction:  [100 100 200 200]
ground truth:  [100 100  50  50]
[[0 0 2]
 [0 2 0]
 [0 0 0]]
              precision    recall  f1-score   support

          50       0.00      0.00      0.00         2
         100       1.00      1.00      1.00         2
         200       0.00      0.00      0.00         0

    accuracy                           0.50         4
   macro avg       0.33      0.33      0.33         4
weighted avg       0.50      0.50      0.50         4

acc= 0.5


Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
